version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/images:/usr/share/nginx/html/images

  backend:
    build: ./backend
    ports:
      - "5000:5000"
